### ISSUE TITLE
[P2] CI omits most workspaces and misses a failing app-shared typecheck

### ISSUE THREAD

**Issue by TwoBar** [Hauddy/hauddy#64]
Reviewed on 2026-09-12 at df32972a0e6ba09538a86a2ad169aa312a88a020 (v0.1.17).

The root build invokes tsc -b with references only to protocol, sdk, hub and sidecar. CI labels this "all packages", but never checks app-shared, app, web, desktop, landing or platform through their typecheck scripts. Current main passes npm test while app-shared's declared typecheck fails.

**Evidence:** [tsconfig.json:1](https://github.com/Hauddy/hauddy/blob/df32972a0e6ba09538a86a2ad169aa312a88a020/tsconfig.json#L1), [.github/workflows/ci.yml:20](https://github.com/Hauddy/hauddy/blob/df32972a0e6ba09538a86a2ad169aa312a88a020/.github/workflows/ci.yml#L20), [packages/app-shared/src/api/index.ts:24](https://github.com/Hauddy/hauddy/blob/df32972a0e6ba09538a86a2ad169aa312a88a020/packages/app-shared/src/api/index.ts#L24), [packages/app-shared/tsconfig.json:1](https://github.com/Hauddy/hauddy/blob/df32972a0e6ba09538a86a2ad169aa312a88a020/packages/app-shared/tsconfig.json#L1).

**Reproduction:** npm test passes all 71 tests. npm run typecheck --workspaces --if-present reports TS2339 at app-shared/src/api/index.ts:24: "Property 'env' does not exist on type 'ImportMeta'." The shared project lacks the ambient Vite env type available to its consuming apps. Other workspace typechecks passed.

**Suggested fix:** Declare the shared package's environment types correctly and run every relevant workspace typecheck in CI. Include isolated platform integration tests in a deliberate CI job; test/*.test.mjs does not include packages/platform/test/p*.mjs.

**Acceptance:** Clean-install CI checks all executable TypeScript workspaces, app-shared typecheck passes independently, and a type error introduced in platform or a renderer fails CI. Keep integration runs local with disposable data.
